import { createSlice } from "@reduxjs/toolkit";

export const employeeListSlice = createSlice({
  name: "employeeList",
  initialState: [
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
    {
      firstName: "a",
      lastName: "a",
      dateOfBirth: "07/11/2005",
      dateOfStart: "06/15/2005",
      street: "a",
      city: "a",
      State: "Alabama",
      abbreviation: "AL",
      zipCode: "11111",
      Department: "Sales",
    },
    {
      firstName: "b",
      lastName: "b",
      dateOfBirth: "07/13/2006",
      dateOfStart: "06/21/2006",
      street: "b",
      city: "b",
      State: "California",
      abbreviation: "CA",
      zipCode: "22222",
      Department: "Marketing",
    },
    {
      firstName: "c",
      lastName: "c",
      dateOfBirth: "07/17/2007",
      dateOfStart: "06/11/2007",
      street: "c",
      city: "c",
      State: "Delaware",
      abbreviation: "DE",
      zipCode: "33333",
      Department: "Engineering",
    },
    {
      firstName: "d",
      lastName: "d",
      dateOfBirth: "08/13/2008",
      dateOfStart: "06/18/2008",
      street: "d",
      city: "d",
      State: "Florida",
      abbreviation: "FL",
      zipCode: "44444",
      Department: "Human Resources",
    },
  ],
  reducers: {
    setEmployeeListData: (state, { payload }) => {
      state.push(payload);
    },
  },
});

export const { setEmployeeListData } = employeeListSlice.actions;
export default employeeListSlice.reducer;
